# Generated by Django 4.0.2 on 2022-04-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_books_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
