# Generated by Django 4.0.2 on 2022-04-05 04:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='expected_delivary_date',
        ),
        migrations.AddField(
            model_name='orders',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 9, 31, 23, 582768), null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='address',
            field=models.CharField(max_length=120),
        ),
    ]
