# Generated by Django 4.0.2 on 2022-04-05 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_orders_expected_delivary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='expected_delivery_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 10, 12, 16, 32, 81831), null=True),
        ),
    ]
